#!/usr/bin/env python3
"""
Generate missing rdfs:comment statement files for ontology anchors.

Fetches comments from W3C sources where available.
"""

import os
import re
from pathlib import Path
from typing import Dict, Set

REPO_ROOT = Path(__file__).parent.parent

# Known comments for OWL vocabulary (from OWL 2 spec)
OWL_COMMENTS = {
    'owl__AllDifferent': 'The class of collections of pairwise different individuals.',
    'owl__AllDisjointClasses': 'The class of collections of pairwise disjoint classes.',
    'owl__AllDisjointProperties': 'The class of collections of pairwise disjoint properties.',
    'owl__Annotation': 'The class of annotated annotations for which the RDF serialization consists of an pointable RDF reification.',
    'owl__AnnotationProperty': 'The class of annotation properties.',
    'owl__AsymmetricProperty': 'The class of asymmetric properties.',
    'owl__Axiom': 'The class of annotated axioms for which the RDF serialization consists of an pointable RDF reification.',
    'owl__Class': 'The class of OWL classes.',
    'owl__DataRange': 'The class of OWL data ranges, which are special kinds of datatypes.',
    'owl__DatatypeProperty': 'The class of data properties.',
    'owl__DeprecatedClass': 'The class of deprecated classes.',
    'owl__DeprecatedProperty': 'The class of deprecated properties.',
    'owl__FunctionalProperty': 'The class of functional properties.',
    'owl__InverseFunctionalProperty': 'The class of inverse-functional properties.',
    'owl__IrreflexiveProperty': 'The class of irreflexive properties.',
    'owl__NamedIndividual': 'The class of named individuals.',
    'owl__NegativePropertyAssertion': 'The class of negative property assertions.',
    'owl__Nothing': 'This is the empty class.',
    'owl__ObjectProperty': 'The class of object properties.',
    'owl__Ontology': 'The class of ontologies.',
    'owl__OntologyProperty': 'The class of ontology properties.',
    'owl__ReflexiveProperty': 'The class of reflexive properties.',
    'owl__Restriction': 'The class of property restrictions.',
    'owl__SymmetricProperty': 'The class of symmetric properties.',
    'owl__Thing': 'The class of OWL individuals.',
    'owl__TransitiveProperty': 'The class of transitive properties.',
    'owl__allValuesFrom': 'The property that determines the class that a universal property restriction refers to.',
    'owl__annotatedProperty': 'The property that determines the predicate of an annotated axiom or annotated annotation.',
    'owl__annotatedSource': 'The property that determines the subject of an annotated axiom or annotated annotation.',
    'owl__annotatedTarget': 'The property that determines the object of an annotated axiom or annotated annotation.',
    'owl__assertionProperty': 'The property that determines the predicate of a negative property assertion.',
    'owl__backwardCompatibleWith': 'The annotation property that indicates that a given ontology is backward compatible with another ontology.',
    'owl__bottomDataProperty': 'The data property that does not relate any individual to any data value.',
    'owl__bottomObjectProperty': 'The object property that does not relate any two individuals.',
    'owl__cardinality': 'The property that determines the cardinality of an exact cardinality restriction.',
    'owl__complementOf': 'The property that determines that a given class is the complement of another class.',
    'owl__datatypeComplementOf': 'The property that determines that a given data range is the complement of another data range with respect to the data domain.',
    'owl__deprecated': 'The annotation property that indicates that a given entity has been deprecated.',
    'owl__differentFrom': 'The property that determines that two given individuals are different.',
    'owl__disjointUnionOf': 'The property that determines that a given class is equivalent to the disjoint union of a collection of other classes.',
    'owl__disjointWith': 'The property that determines that two given classes are disjoint.',
    'owl__distinctMembers': 'The property that determines the collection of pairwise different individuals in a owl:AllDifferent axiom.',
    'owl__equivalentClass': 'The property that determines that two given classes are equivalent, and that is used to specify datatype definitions.',
    'owl__equivalentProperty': 'The property that determines that two given properties are equivalent.',
    'owl__hasKey': 'The property that determines the collection of properties that jointly build a key.',
    'owl__hasSelf': 'The property that determines the property that a self restriction refers to.',
    'owl__hasValue': 'The property that determines the individual that a has-value restriction refers to.',
    'owl__imports': 'The property that is used for importing other ontologies into a given ontology.',
    'owl__incompatibleWith': 'The annotation property that indicates that a given ontology is incompatible with another ontology.',
    'owl__intersectionOf': 'The property that determines the collection of classes or data ranges that build an intersection.',
    'owl__inverseOf': 'The property that determines that two given properties are inverse.',
    'owl__maxCardinality': 'The property that determines the cardinality of a maximum cardinality restriction.',
    'owl__maxQualifiedCardinality': 'The property that determines the cardinality of a maximum qualified cardinality restriction.',
    'owl__members': 'The property that determines the collection of members in either a owl:AllDifferent, owl:AllDisjointClasses or owl:AllDisjointProperties axiom.',
    'owl__minCardinality': 'The property that determines the cardinality of a minimum cardinality restriction.',
    'owl__minQualifiedCardinality': 'The property that determines the cardinality of a minimum qualified cardinality restriction.',
    'owl__onClass': 'The property that determines the class that a qualified object cardinality restriction refers to.',
    'owl__onDataRange': 'The property that determines the data range that a qualified data cardinality restriction refers to.',
    'owl__onDatatype': 'The property that determines the datatype that a datatype restriction refers to.',
    'owl__onProperties': 'The property that determines the n-tuple of properties that a property restriction on an n-ary data range refers to.',
    'owl__onProperty': 'The property that determines the property that a property restriction refers to.',
    'owl__oneOf': 'The property that determines the collection of individuals or data values that build an enumeration.',
    'owl__priorVersion': 'The annotation property that indicates the predecessor ontology of a given ontology.',
    'owl__propertyChainAxiom': 'The property that determines the n-tuple of properties that build a sub property chain of a given property.',
    'owl__propertyDisjointWith': 'The property that determines that two given properties are disjoint.',
    'owl__qualifiedCardinality': 'The property that determines the cardinality of an exact qualified cardinality restriction.',
    'owl__sameAs': 'The property that determines that two given individuals are equal.',
    'owl__someValuesFrom': 'The property that determines the class that an existential property restriction refers to.',
    'owl__sourceIndividual': 'The property that determines the subject of a negative property assertion.',
    'owl__targetIndividual': 'The property that determines the object of a negative object property assertion.',
    'owl__targetValue': 'The property that determines the value of a negative data property assertion.',
    'owl__topDataProperty': 'The data property that relates every individual to every data value.',
    'owl__topObjectProperty': 'The object property that relates every two individuals.',
    'owl__unionOf': 'The property that determines the collection of classes or data ranges that build a union.',
    'owl__versionIRI': 'The property that identifies the version IRI of an ontology.',
    'owl__versionInfo': 'The annotation property that provides version information for an ontology or another OWL construct.',
    'owl__withRestrictions': 'The property that determines the collection of facet-value pairs that define a datatype restriction.',
}

# Known comments for DCTERMS (from Dublin Core spec)
DCTERMS_COMMENTS = {
    'dcterms__Agent': 'A resource that acts or has the power to act.',
    'dcterms__AgentClass': 'A group of agents.',
    'dcterms__BibliographicResource': 'A book, article, or other documentary resource.',
    'dcterms__FileFormat': 'A digital resource format.',
    'dcterms__Frequency': 'A rate at which something recurs.',
    'dcterms__Jurisdiction': 'The extent or range of judicial, law enforcement, or other authority.',
    'dcterms__LicenseDocument': 'A legal document giving official permission to do something with a resource.',
    'dcterms__LinguisticSystem': 'A system of signs, symbols, sounds, gestures, or rules used in communication.',
    'dcterms__Location': 'A spatial region or named place.',
    'dcterms__LocationPeriodOrJurisdiction': 'A location, period of time, or jurisdiction.',
    'dcterms__MediaType': 'A file format or physical medium.',
    'dcterms__MediaTypeOrExtent': 'A media type or extent.',
    'dcterms__MethodOfAccrual': 'A method by which resources are added to a collection.',
    'dcterms__MethodOfInstruction': 'A process that is used to engender knowledge, attitudes, and skills.',
    'dcterms__PeriodOfTime': 'An interval of time that is named or defined by its start and end dates.',
    'dcterms__PhysicalMedium': 'A physical material or carrier.',
    'dcterms__PhysicalResource': 'A material thing.',
    'dcterms__Policy': 'A plan or course of action by an authority, intended to influence and determine decisions, actions, and other matters.',
    'dcterms__ProvenanceStatement': 'Any changes in ownership and custody of a resource since its creation that are significant for its authenticity, integrity, and interpretation.',
    'dcterms__RightsStatement': 'A statement about the intellectual property rights (IPR) held in or over a resource.',
    'dcterms__SizeOrDuration': 'A dimension or extent, or a time taken to play or execute.',
    'dcterms__Standard': 'A reference point against which other things can be evaluated or compared.',
    'dcterms__abstract': 'A summary of the resource.',
    'dcterms__accessRights': 'Information about who access the resource or an indication of its security status.',
    'dcterms__accrualMethod': 'The method by which items are added to a collection.',
    'dcterms__accrualPeriodicity': 'The frequency with which items are added to a collection.',
    'dcterms__accrualPolicy': 'The policy governing the addition of items to a collection.',
    'dcterms__alternative': 'An alternative name for the resource.',
    'dcterms__audience': 'A class of agents for whom the resource is intended or useful.',
    'dcterms__available': 'Date that the resource became or will become available.',
    'dcterms__bibliographicCitation': 'A bibliographic reference for the resource.',
    'dcterms__conformsTo': 'An established standard to which the described resource conforms.',
    'dcterms__contributor': 'An entity responsible for making contributions to the resource.',
    'dcterms__coverage': 'The spatial or temporal topic of the resource.',
    'dcterms__created': 'Date of creation of the resource.',
    'dcterms__creator': 'An entity responsible for making the resource.',
    'dcterms__date': 'A point or period of time associated with an event in the lifecycle of the resource.',
    'dcterms__dateAccepted': 'Date of acceptance of the resource.',
    'dcterms__dateCopyrighted': 'Date of copyright of the resource.',
    'dcterms__dateSubmitted': 'Date of submission of the resource.',
    'dcterms__description': 'An account of the resource.',
    'dcterms__educationLevel': 'A class of agents, defined in terms of progression through an educational or training context, for which the described resource is intended.',
    'dcterms__extent': 'The size or duration of the resource.',
    'dcterms__format': 'The file format, physical medium, or dimensions of the resource.',
    'dcterms__hasFormat': 'A related resource that is substantially the same as the pre-existing described resource, but in another format.',
    'dcterms__hasPart': 'A related resource that is included either physically or logically in the described resource.',
    'dcterms__hasVersion': 'A related resource that is a version, edition, or adaptation of the described resource.',
    'dcterms__identifier': 'An unambiguous reference to the resource within a given context.',
    'dcterms__instructionalMethod': 'A process, used to engender knowledge, attitudes and skills, that the described resource is designed to support.',
    'dcterms__isFormatOf': 'A pre-existing related resource that is substantially the same as the described resource, but in another format.',
    'dcterms__isPartOf': 'A related resource in which the described resource is physically or logically included.',
    'dcterms__isReferencedBy': 'A related resource that references, cites, or otherwise points to the described resource.',
    'dcterms__isReplacedBy': 'A related resource that supplants, displaces, or supersedes the described resource.',
    'dcterms__isRequiredBy': 'A related resource that requires the described resource to support its function, delivery, or coherence.',
    'dcterms__isVersionOf': 'A related resource of which the described resource is a version, edition, or adaptation.',
    'dcterms__issued': 'Date of formal issuance of the resource.',
    'dcterms__language': 'A language of the resource.',
    'dcterms__license': 'A legal document giving official permission to do something with the resource.',
    'dcterms__mediator': 'An entity that mediates access to the resource.',
    'dcterms__medium': 'The material or physical carrier of the resource.',
    'dcterms__modified': 'Date on which the resource was changed.',
    'dcterms__provenance': 'A statement of any changes in ownership and custody of the resource since its creation that are significant for its authenticity, integrity, and interpretation.',
    'dcterms__publisher': 'An entity responsible for making the resource available.',
    'dcterms__references': 'A related resource that is referenced, cited, or otherwise pointed to by the described resource.',
    'dcterms__relation': 'A related resource.',
    'dcterms__replaces': 'A related resource that is supplanted, displaced, or superseded by the described resource.',
    'dcterms__requires': 'A related resource that is required by the described resource to support its function, delivery, or coherence.',
    'dcterms__rights': 'Information about rights held in and over the resource.',
    'dcterms__rightsHolder': 'A person or organization owning or managing rights over the resource.',
    'dcterms__source': 'A related resource from which the described resource is derived.',
    'dcterms__spatial': 'Spatial characteristics of the resource.',
    'dcterms__subject': 'A topic of the resource.',
    'dcterms__tableOfContents': 'A list of subunits of the resource.',
    'dcterms__temporal': 'Temporal characteristics of the resource.',
    'dcterms__title': 'A name given to the resource.',
    'dcterms__type': 'The nature or genre of the resource.',
    'dcterms__valid': 'Date (often a range) of validity of a resource.',
}

# Known comments for SKOS
SKOS_COMMENTS = {
    'skos__Collection': 'A meaningful collection of concepts.',
    'skos__Concept': 'An idea or notion; a unit of thought.',
    'skos__ConceptScheme': 'A set of concepts, optionally including statements about semantic relationships between those concepts.',
    'skos__OrderedCollection': 'An ordered collection of concepts, where both the grouping and the ordering are meaningful.',
    'skos__altLabel': 'An alternative lexical label for a resource.',
    'skos__broadMatch': 'skos:broadMatch is used to state a hierarchical mapping link between two conceptual resources in different concept schemes.',
    'skos__broader': 'Relates a concept to a concept that is more general in meaning.',
    'skos__broaderTransitive': 'skos:broaderTransitive is a transitive superproperty of skos:broader.',
    'skos__changeNote': 'A note about a modification to a concept.',
    'skos__closeMatch': 'skos:closeMatch is used to link two concepts that are sufficiently similar that they can be used interchangeably in some information retrieval applications.',
    'skos__definition': 'A statement or formal explanation of the meaning of a concept.',
    'skos__editorialNote': 'A note for an editor, translator or maintainer of the vocabulary.',
    'skos__exactMatch': 'skos:exactMatch is used to link two concepts, indicating a high degree of confidence that the concepts can be used interchangeably across a wide range of information retrieval applications.',
    'skos__example': 'An example of the use of a concept.',
    'skos__hasTopConcept': 'Relates, by convention, a concept scheme to a concept which is topmost in the broader/narrower concept hierarchies for that scheme, providing an entry point to these hierarchies.',
    'skos__hiddenLabel': 'A lexical label for a resource that should be hidden when generating visual displays of the resource, but should still be accessible to free text search operations.',
    'skos__historyNote': 'A note about the past state/use/meaning of a concept.',
    'skos__inScheme': 'Relates a resource (for example a concept) to a concept scheme in which it is included.',
    'skos__mappingRelation': 'Relates two concepts coming, by convention, from different schemes, and that have comparable meanings.',
    'skos__member': 'Relates a collection to one of its members.',
    'skos__memberList': 'Relates an ordered collection to the RDF list containing its members.',
    'skos__narrowMatch': 'skos:narrowMatch is used to state a hierarchical mapping link between two conceptual resources in different concept schemes.',
    'skos__narrower': 'Relates a concept to a concept that is more specific in meaning.',
    'skos__narrowerTransitive': 'skos:narrowerTransitive is a transitive superproperty of skos:narrower.',
    'skos__notation': 'A notation, also known as classification code, is a string of characters such as "T58.5" or "303.4833" used to uniquely identify a concept within the scope of a given concept scheme.',
    'skos__note': 'A general note, for any purpose.',
    'skos__prefLabel': 'The preferred lexical label for a resource, in a given language.',
    'skos__related': 'Relates a concept to a concept with which there is an associative semantic relationship.',
    'skos__relatedMatch': 'skos:relatedMatch is used to state an associative mapping link between two conceptual resources in different concept schemes.',
    'skos__scopeNote': 'A note that helps to clarify the meaning and/or the use of a concept.',
    'skos__semanticRelation': 'Links a concept to a concept related by meaning.',
    'skos__topConceptOf': 'Relates a concept to the concept scheme that it is a top level concept of.',
}

# Known comments for FOAF
FOAF_COMMENTS = {
    'foaf__Agent': 'An agent (eg. person, group, software or physical artifact).',
    'foaf__Document': 'A document.',
    'foaf__Group': 'A class of Agents.',
    'foaf__Image': 'An image.',
    'foaf__LabelProperty': 'A foaf:LabelProperty is any RDF property with texual values that serve as labels.',
    'foaf__OnlineAccount': 'An online account.',
    'foaf__OnlineChatAccount': 'An online chat account.',
    'foaf__OnlineEcommerceAccount': 'An online e-commerce account.',
    'foaf__OnlineGamingAccount': 'An online gaming account.',
    'foaf__Organization': 'An organization.',
    'foaf__Person': 'A person.',
    'foaf__PersonalProfileDocument': 'A personal profile RDF document.',
    'foaf__Project': 'A project (a collective endeavour of some kind).',
    'foaf__account': 'Indicates an account held by this agent.',
    'foaf__accountName': 'Indicates the name (identifier) associated with this online account.',
    'foaf__accountServiceHomepage': 'Indicates a homepage of the service provide for this online account.',
    'foaf__age': 'The age in years of some agent.',
    'foaf__aimChatID': 'An AIM chat ID.',
    'foaf__based_near': 'A location that something is based near, for some broadly human notion of near.',
    'foaf__birthday': 'The birthday of this Agent, represented in mm-dd string form, eg. "12-31".',
    'foaf__currentProject': 'A current project this person works on.',
    'foaf__depiction': 'A depiction of some thing.',
    'foaf__depicts': 'A thing depicted in this representation.',
    'foaf__dnaChecksum': 'A checksum for the DNA of some thing. Joke.',
    'foaf__familyName': 'The family name of some person.',
    'foaf__firstName': 'The first name of a person.',
    'foaf__focus': 'The underlying or "focal" entity associated with some SKOS-described concept.',
    'foaf__fundedBy': 'An organization funding a project or person.',
    'foaf__geekcode': 'A textual geekcode for this person, see http://www.geekcode.com/geek.html.',
    'foaf__gender': 'The gender of this Agent (typically but not necessarily "male" or "female").',
    'foaf__givenName': 'The given name of some person.',
    'foaf__holdsAccount': 'Indicates an account held by this agent.',
    'foaf__homepage': 'A homepage for some thing.',
    'foaf__icqChatID': 'An ICQ chat ID.',
    'foaf__img': 'An image that can be used to represent some thing (ie. those depictions which are particularly representative of something, eg. ones profile photo).',
    'foaf__interest': 'A page about a topic of interest to this person.',
    'foaf__isPrimaryTopicOf': 'A document that this thing is the primary topic of.',
    'foaf__jabberID': 'A jabber ID for something.',
    'foaf__knows': 'A person known by this person (indicating some level of reciprocated interaction between the parties).',
    'foaf__lastName': 'The last name of a person.',
    'foaf__logo': 'A logo representing some thing.',
    'foaf__made': 'Something that was made by this agent.',
    'foaf__maker': 'An agent that made this thing.',
    'foaf__mbox': 'A personal mailbox, ie. an Internet mailbox associated with exactly one owner.',
    'foaf__mbox_sha1sum': 'The sha1sum of the URI of an Internet mailbox associated with exactly one owner.',
    'foaf__member': 'Indicates a member of a Group.',
    'foaf__membershipClass': 'Indicates the class of individuals that are a member of a Group.',
    'foaf__msnChatID': 'An MSN chat ID.',
    'foaf__myersBriggs': 'A Myers Briggs (MBTI) personality classification.',
    'foaf__name': 'A name for some thing.',
    'foaf__nick': 'A short informal nickname characterising an agent.',
    'foaf__openid': 'An OpenID for an Agent.',
    'foaf__page': 'A page or document about this thing.',
    'foaf__pastProject': 'A project this person has previously worked on.',
    'foaf__phone': 'A phone, specified using fully qualified tel: URI scheme.',
    'foaf__plan': 'A .plan comment, in the tradition of finger and .teletubbies directory.',
    'foaf__primaryTopic': 'The primary topic of some page or document.',
    'foaf__publications': 'A link to the publications of this person.',
    'foaf__schoolHomepage': 'A homepage of a school attended by the person.',
    'foaf__sha1': 'A sha1sum hash, in hex.',
    'foaf__skypeID': 'A Skype ID.',
    'foaf__status': 'A string expressing what the user is happy for the general public (normally combats spam) to know about their current activity.',
    'foaf__surname': 'The surname of some person.',
    'foaf__theme': 'A theme.',
    'foaf__thumbnail': 'A derived thumbnail image.',
    'foaf__tipjar': 'A tipjar document for this agent, describing means for payment and reception of payment.',
    'foaf__title': 'Title (Mr, Mrs, Ms, Dr. etc).',
    'foaf__topic': 'A topic of some page or document.',
    'foaf__topic_interest': 'A thing of interest to this person.',
    'foaf__weblog': 'A weblog of some thing (whether person, group, company etc.).',
    'foaf__workInfoHomepage': 'A work info homepage of some person; a page about their work for some organization.',
    'foaf__workplaceHomepage': 'A workplace homepage of some person; the homepage of an organization they work for.',
    'foaf__yahooChatID': 'A Yahoo chat ID.',
}

# Known comments for PROV-O
PROV_COMMENTS = {
    'prov__Activity': 'An activity is something that occurs over a period of time and acts upon or with entities.',
    'prov__ActivityInfluence': 'ActivityInfluence provides additional descriptions of an Activity\'s binary influence upon any other kind of resource.',
    'prov__Agent': 'An agent is something that bears some form of responsibility for an activity taking place.',
    'prov__AgentInfluence': 'AgentInfluence provides additional descriptions of an Agent\'s binary influence upon any other kind of resource.',
    'prov__Association': 'An activity association is an assignment of responsibility to an agent for an activity.',
    'prov__Attribution': 'Attribution is the ascribing of an entity to an agent.',
    'prov__Bundle': 'A bundle is a named set of provenance descriptions.',
    'prov__Collection': 'A collection is an entity that provides a structure to some constituents that must themselves be entities.',
    'prov__Communication': 'Communication is the exchange of some unspecified entity by two activities.',
    'prov__Delegation': 'Delegation is the assignment of authority and responsibility to an agent by itself or by another agent.',
    'prov__Derivation': 'A derivation is a transformation of an entity into another.',
    'prov__EmptyCollection': 'An empty collection is a collection without members.',
    'prov__End': 'End is when an activity is deemed to have been ended by an entity.',
    'prov__Entity': 'An entity is a physical, digital, conceptual, or other kind of thing with some fixed aspects.',
    'prov__EntityInfluence': 'EntityInfluence provides additional descriptions of an Entity\'s binary influence upon any other kind of resource.',
    'prov__Generation': 'Generation is the completion of production of a new entity by an activity.',
    'prov__Influence': 'Influence is the capacity of an entity, activity, or agent to have an effect on the character, development, or behavior of another.',
    'prov__Location': 'A location can be an identifiable geographic place, or an extent such as a line or area.',
    'prov__Organization': 'An organization is a social or legal institution such as a company, society, etc.',
    'prov__Person': 'Person agents are people.',
    'prov__Plan': 'A plan is an entity that represents a set of actions or steps intended by one or more agents.',
    'prov__Role': 'A role is the function of an entity or agent with respect to an activity.',
    'prov__SoftwareAgent': 'A software agent is running software.',
    'prov__Start': 'Start is when an activity is deemed to have been started by an entity.',
    'prov__Usage': 'Usage is the beginning of utilizing an entity by an activity.',
    'prov__actedOnBehalfOf': 'An object property to express the accountability of an agent towards another agent.',
    'prov__alternateOf': 'Two alternate entities present aspects of the same thing.',
    'prov__atLocation': 'A location for any Activity, Entity, or Agent.',
    'prov__atTime': 'The time at which an InstantaneousEvent occurred.',
    'prov__endedAtTime': 'The time at which an activity ended.',
    'prov__generated': 'Generation is the completion of production of a new entity by an activity.',
    'prov__generatedAtTime': 'The time at which an entity was completely created.',
    'prov__hadActivity': 'The _optional_ Activity of an Influence.',
    'prov__hadGeneration': 'The _optional_ Generation involved in an Entity\'s Derivation.',
    'prov__hadMember': 'A collection has members.',
    'prov__hadPlan': 'The _optional_ Plan adopted by an Agent in Association with some Activity.',
    'prov__hadPrimarySource': 'A derivation for which the source entity is a primary source.',
    'prov__hadRole': 'A role played by an entity or agent.',
    'prov__hadUsage': 'The _optional_ Usage involved in an Entity\'s Derivation.',
    'prov__hasActivity': 'This property points to an Activity.',
    'prov__hasAgent': 'This property points to an Agent.',
    'prov__hasEntity': 'This property points to an Entity.',
    'prov__influencer': 'This property is used as part of the qualified influence pattern.',
    'prov__invalidated': 'Invalidation is the start of the destruction, cessation, or expiry of an existing entity.',
    'prov__invalidatedAtTime': 'The time at which an entity was invalidated.',
    'prov__qualifiedAssociation': 'If this Activity prov:wasAssociatedWith Agent, then it can qualify the Association using prov:qualifiedAssociation.',
    'prov__qualifiedAttribution': 'If this Entity prov:wasAttributedTo Agent, then it can qualify how it was influenced using prov:qualifiedAttribution.',
    'prov__qualifiedCommunication': 'If this Activity prov:wasInformedBy Activity, then it can qualify how it was influenced using prov:qualifiedCommunication.',
    'prov__qualifiedDelegation': 'If this Agent prov:actedOnBehalfOf Agent, then it can qualify how with prov:qualifiedDelegation.',
    'prov__qualifiedDerivation': 'If this Entity prov:wasDerivedFrom Entity, then it can qualify how it was derived using prov:qualifiedDerivation.',
    'prov__qualifiedEnd': 'If this Activity prov:wasEndedBy Entity, then it can qualify how it was ended using prov:qualifiedEnd.',
    'prov__qualifiedGeneration': 'If this Activity prov:generated Entity, then it can qualify how it performed the Generation using prov:qualifiedGeneration.',
    'prov__qualifiedInfluence': 'Because prov:qualifiedInfluence is a broad relation, the more specific relations should be used when applicable.',
    'prov__qualifiedStart': 'If this Activity prov:wasStartedBy Entity, then it can qualify how it was started using prov:qualifiedStart.',
    'prov__qualifiedUsage': 'If this Activity prov:used Entity, then it can qualify how it used it using prov:qualifiedUsage.',
    'prov__specializationOf': 'An entity that is a specialization of another shares all aspects of the latter.',
    'prov__startedAtTime': 'The time at which an activity started.',
    'prov__used': 'A prov:Entity that was used by this prov:Activity.',
    'prov__value': 'Provides a value that is a direct representation of an entity.',
    'prov__wasAttributedTo': 'Attribution is the ascribing of an entity to an agent.',
    'prov__wasDerivedFrom': 'The more specific subproperties of prov:wasDerivedFrom should be used when applicable.',
    'prov__wasEndedBy': 'End is when an activity is deemed to have ended.',
    'prov__wasGeneratedBy': 'Generation is the completion of production of a new entity by an activity.',
    'prov__wasInformedBy': 'An activity a2 is dependent on or informed by another activity a1.',
    'prov__wasInvalidatedBy': 'Invalidation is the start of the destruction, cessation, or expiry of an existing entity.',
    'prov__wasQuotedFrom': 'An entity is derived from an original entity by copying, or quoting, some or all of it.',
    'prov__wasRevisionOf': 'A revision is a derivation for which the resulting entity is a revised version of some original.',
    'prov__wasStartedBy': 'Start is when an activity is deemed to have started.',
}

# Known comments for OWL-Time ontology
TIME_COMMENTS = {
    'time__April': 'April',
    'time__August': 'August',
    'time__DateTimeDescription': 'Description of date and time structured with separate values for the various elements of a calendar-clock system.',
    'time__DateTimeInterval': 'DateTimeInterval is a subclass of ProperInterval that uses points in time as beginning and end.',
    'time__DayOfWeek': 'The day of week.',
    'time__December': 'December',
    'time__Duration': 'Duration of a temporal extent expressed as a number scaled by a temporal unit.',
    'time__DurationDescription': 'Description of temporal extent structured with separate values for the various elements of a calendar-clock system.',
    'time__February': 'February',
    'time__Friday': 'Friday',
    'time__GeneralDateTimeDescription': 'Description of date and time structured with separate values for the various elements of a calendar-clock system.',
    'time__GeneralDurationDescription': 'Description of temporal extent structured with separate values for the various elements of a calendar-clock system.',
    'time__Instant': 'A temporal entity with zero extent or duration.',
    'time__Interval': 'A temporal entity with an extent or duration.',
    'time__January': 'January',
    'time__July': 'July',
    'time__June': 'June',
    'time__March': 'March',
    'time__May': 'May',
    'time__Monday': 'Monday',
    'time__MonthOfYear': 'The month of the year.',
    'time__November': 'November',
    'time__October': 'October',
    'time__ProperInterval': 'A temporal entity with non-zero extent or duration.',
    'time__Saturday': 'Saturday',
    'time__September': 'September',
    'time__Sunday': 'Sunday',
    'time__TemporalDuration': 'Time extent; duration of a time interval separate from its particular start or end position.',
    'time__TemporalEntity': 'A temporal interval or instant.',
    'time__TemporalPosition': 'A position on a time-line.',
    'time__Thursday': 'Thursday',
    'time__TimePosition': 'A temporal position described using either a (nominal) value from an ordinal reference system, or a (numeric) value in a temporal coordinate system.',
    'time__TimeZone': 'A Time Zone specifies the amount by which the local time is offset from UTC.',
    'time__Tuesday': 'Tuesday',
    'time__Wednesday': 'Wednesday',
    'time__after': 'Gives directionality to time. If a temporal entity T1 is after another temporal entity T2, then the beginning of T1 is after the end of T2.',
    'time__before': 'Gives directionality to time. If a temporal entity T1 is before another temporal entity T2, then the end of T1 is before the beginning of T2.',
    'time__day': 'Day position in a calendar-clock system. The range of this property is not specified, so can be replaced by any specific representation of a calendar day from any calendar.',
    'time__dayOfWeek': 'The day of week, whose value is a member of the class time:DayOfWeek.',
    'time__dayOfYear': 'The number of the day within the year.',
    'time__days': 'Length of, or element of the length of, a temporal extent expressed in days.',
    'time__hasBeginning': 'Beginning of a temporal entity.',
    'time__hasDateTimeDescription': 'Value of DateTimeInterval expressed as a structured value.',
    'time__hasDayOfWeek': 'The day of the week on which a calendar-clock description falls.',
    'time__hasDuration': 'Duration of a temporal entity, expressed as a scaled value or nominal value.',
    'time__hasDurationDescription': 'Duration of a temporal entity, expressed using a structured description.',
    'time__hasEnd': 'End of a temporal entity.',
    'time__hasMonthOfYear': 'The month of the year on which a calendar-clock description falls.',
    'time__hasTRS': 'The temporal reference system used by a temporal position or extent description.',
    'time__hasTime': 'Supports the association of a temporal entity with a feature.',
    'time__hasTimeZone': 'The time zone for clock elements in the temporal position or extent description.',
    'time__hour': 'Hour position in a calendar-clock system.',
    'time__hours': 'Length of, or element of the length of, a temporal extent expressed in hours.',
    'time__inDateTime': 'Position of an instant, expressed using a structured description.',
    'time__inTemporalPosition': 'Position of an instant, expressed as a temporal coordinate or nominal value.',
    'time__inTimePosition': 'Position of an instant, expressed as a temporal coordinate or nominal value.',
    'time__inXSDDate': 'Position of an instant, expressed using xsd:date.',
    'time__inXSDDateTime': 'Position of an instant, expressed using xsd:dateTime.',
    'time__inXSDDateTimeStamp': 'Position of an instant, expressed using xsd:dateTimeStamp.',
    'time__inXSDgYear': 'Position of an instant, expressed using xsd:gYear.',
    'time__inXSDgYearMonth': 'Position of an instant, expressed using xsd:gYearMonth.',
    'time__inside': 'An instant that falls inside the interval.',
    'time__intervalAfter': 'If a proper interval T1 is intervalAfter another proper interval T2, then the beginning of T1 is after the end of T2.',
    'time__intervalBefore': 'If a proper interval T1 is intervalBefore another proper interval T2, then the end of T1 is before the beginning of T2.',
    'time__intervalContains': 'If a proper interval T1 is intervalContains another proper interval T2, then the beginning of T1 is before the beginning of T2, and the end of T1 is after the end of T2.',
    'time__intervalDisjoint': 'If a proper interval T1 is intervalDisjoint another proper interval T2, then the end of T1 is before the beginning of T2, or the end of T2 is before the beginning of T1, i.e. the intervals do not overlap in any way.',
    'time__intervalDuring': 'If a proper interval T1 is intervalDuring another proper interval T2, then the beginning of T1 is after the beginning of T2, and the end of T1 is before the end of T2.',
    'time__intervalEquals': 'If a proper interval T1 is intervalEquals another proper interval T2, then the beginning of T1 is coincident with the beginning of T2, and the end of T1 is coincident with the end of T2.',
    'time__intervalFinishedBy': 'If a proper interval T1 is intervalFinishedBy another proper interval T2, then the beginning of T1 is before the beginning of T2, and the end of T1 is coincident with the end of T2.',
    'time__intervalFinishes': 'If a proper interval T1 is intervalFinishes another proper interval T2, then the beginning of T1 is after the beginning of T2, and the end of T1 is coincident with the end of T2.',
    'time__intervalIn': 'If a proper interval T1 is intervalIn another proper interval T2, then the beginning of T1 is after or coincident with the beginning of T2, and the end of T1 is before or coincident with the end of T2.',
    'time__intervalMeets': 'If a proper interval T1 is intervalMeets another proper interval T2, then the end of T1 is coincident with the beginning of T2.',
    'time__intervalMetBy': 'If a proper interval T1 is intervalMetBy another proper interval T2, then the beginning of T1 is coincident with the end of T2.',
    'time__intervalOverlappedBy': 'If a proper interval T1 is intervalOverlappedBy another proper interval T2, then the beginning of T1 is after the beginning of T2, and the beginning of T1 is before the end of T2, and the end of T1 is after the end of T2.',
    'time__intervalOverlaps': 'If a proper interval T1 is intervalOverlaps another proper interval T2, then the beginning of T1 is before the beginning of T2, and the end of T1 is after the beginning of T2, and the end of T1 is before the end of T2.',
    'time__intervalStartedBy': 'If a proper interval T1 is intervalStartedBy another proper interval T2, then the beginning of T1 is coincident with the beginning of T2, and the end of T1 is after the end of T2.',
    'time__intervalStarts': 'If a proper interval T1 is intervalStarts another proper interval T2, then the beginning of T1 is coincident with the beginning of T2, and the end of T1 is before the end of T2.',
    'time__minute': 'Minute position in a calendar-clock system.',
    'time__minutes': 'Length of, or element of the length of, a temporal extent expressed in minutes.',
    'time__month': 'Month position in a calendar-clock system. The range of this property is not specified, so can be replaced by any specific representation of a calendar month from any calendar.',
    'time__months': 'Length of, or element of the length of, a temporal extent expressed in months.',
    'time__numericDuration': 'Value of a temporal extent expressed as a number scaled by a temporal unit.',
    'time__numericPosition': 'The (numeric) position of an instant in a coordinate system.',
    'time__second': 'Second position in a calendar-clock system.',
    'time__seconds': 'Length of, or element of the length of, a temporal extent expressed in seconds.',
    'time__unitType': 'The temporal unit which provides the precision of a date-time value or scale of a temporal extent.',
    'time__week': 'Week position in a calendar-clock system.',
    'time__weeks': 'Length of, or element of the length of, a temporal extent expressed in weeks.',
    'time__year': 'Year position in a calendar-clock system.',
    'time__years': 'Length of, or element of the length of, a temporal extent expressed in years.',
}

# Known comments for vCard ontology
VCARD_COMMENTS = {
    'vcard__Acquaintance': 'The Acquaintance relation type.',
    'vcard__Address': 'To specify the components of the delivery address for the vCard object.',
    'vcard__Agent': 'The Agent type.',
    'vcard__Cell': 'The Cell type.',
    'vcard__Child': 'The Child relation type.',
    'vcard__Colleague': 'The Colleague relation type.',
    'vcard__Contact': 'The Contact relation type.',
    'vcard__Coresident': 'The Coresident relation type.',
    'vcard__Coworker': 'The Coworker relation type.',
    'vcard__Crush': 'The Crush relation type.',
    'vcard__Date': 'The Date type.',
    'vcard__Email': 'The Email type.',
    'vcard__Emergency': 'The Emergency relation type.',
    'vcard__Fax': 'The Fax type.',
    'vcard__Friend': 'The Friend relation type.',
    'vcard__Gender': 'Used for gender codes. The URI of the gender code must be used as the value for Gender.',
    'vcard__Group': 'Object representing a group of persons or entities.',
    'vcard__Home': 'The Home type.',
    'vcard__Individual': 'An object representing a single person or entity.',
    'vcard__Kin': 'The Kin relation type.',
    'vcard__Kind': 'The parent class for all objects.',
    'vcard__Location': 'An object representing a named geographical place.',
    'vcard__Me': 'The Me relation type.',
    'vcard__Met': 'The Met relation type.',
    'vcard__Muse': 'The Muse relation type.',
    'vcard__Name': 'To specify the components of the name of the object.',
    'vcard__Neighbor': 'The Neighbor relation type.',
    'vcard__Organization': 'An object representing an organization.',
    'vcard__Pager': 'The Pager type.',
    'vcard__Parent': 'The Parent relation type.',
    'vcard__Sibling': 'The Sibling relation type.',
    'vcard__Spouse': 'The Spouse relation type.',
    'vcard__Sweetheart': 'The Sweetheart relation type.',
    'vcard__Telephone': 'The Telephone type.',
    'vcard__TelephoneType': 'Used for telephone type codes. The URI of the telephone type code must be used as the value for Telephone Type.',
    'vcard__Text': 'The Text type.',
    'vcard__VCard': 'The vCard class is equivalent to the new Kind class, which is the parent for the four explicit types of vCards (Individual, Organization, Location, Group).',
    'vcard__Video': 'The Video type.',
    'vcard__Voice': 'The Voice type.',
    'vcard__Work': 'The Work type.',
    'vcard__additional-name': 'The additional name associated with the object.',
    'vcard__adr': 'To specify the components of the delivery address for the vCard object.',
    'vcard__anniversary': 'The date of marriage, or equivalent, of the object.',
    'vcard__bday': 'To specify the birth date of the object.',
    'vcard__categories': 'The category information about the object, also known as tags.',
    'vcard__country-name': 'The country name associated with the address of the object.',
    'vcard__extended-address': 'The extended address, such as apartment number, of the object.',
    'vcard__family-name': 'The family name associated with the object.',
    'vcard__fn': 'The formatted text corresponding to the name of the object.',
    'vcard__geo': 'The geographic location of the object.',
    'vcard__given-name': 'The given name associated with the object.',
    'vcard__hasAddress': 'To specify the components of the delivery address for the object.',
    'vcard__hasCalendarBusy': 'To specify the busy time associated with the object.',
    'vcard__hasCalendarLink': 'To specify the calendar associated with the object.',
    'vcard__hasCalendarRequest': 'To specify the calendar user address to which a scheduling request should be sent for the object.',
    'vcard__hasEmail': 'To specify the electronic mail address for communication with the object.',
    'vcard__hasGender': 'To specify the gender of the object.',
    'vcard__hasGeo': 'To specify information related to the global positioning of the object.',
    'vcard__hasKey': 'To specify a public key or authentication certificate associated with the object.',
    'vcard__hasLogo': 'To specify a graphic image of a logo associated with the object.',
    'vcard__hasName': 'To specify the components of the name of the object.',
    'vcard__hasOrganizationName': 'To specify the organizational name associated with the object.',
    'vcard__hasOrganizationUnit': 'To specify the organizational unit name associated with the object.',
    'vcard__hasPhoto': 'To specify an image or photograph information that annotates some aspect of the object.',
    'vcard__hasSound': 'To specify a digital sound content information that annotates some aspect of the object.',
    'vcard__hasTelephone': 'To specify the telephone number for telephony communication with the object.',
    'vcard__hasUID': 'To specify a value that represents a globally unique identifier corresponding to the object.',
    'vcard__hasURL': 'To specify a uniform resource locator associated with the object.',
    'vcard__hasValue': 'Used to indicate the resource value of an object property that requires property parameters.',
    'vcard__honorific-prefix': 'The honorific prefix of the name associated with the object.',
    'vcard__honorific-suffix': 'The honorific suffix of the name associated with the object.',
    'vcard__key': 'To specify a public key or authentication certificate associated with the object.',
    'vcard__language': 'To specify the language(s) that may be used for contacting the entity associated with the vCard.',
    'vcard__locality': 'The locality (e.g., city) associated with the address of the object.',
    'vcard__logo': 'To specify a graphic image of a logo associated with the object.',
    'vcard__member': 'To include a member in the group this vCard represents.',
    'vcard__n': 'To specify the components of the name of the object.',
    'vcard__nickname': 'The nickname associated with the object.',
    'vcard__note': 'A note associated with the object.',
    'vcard__org': 'To specify the organizational name and units associated with the vCard.',
    'vcard__photo': 'To specify an image or photograph information that annotates some aspect of the object.',
    'vcard__po-box': 'The post office box associated with the address of the object.',
    'vcard__post-office-box': 'The post office box associated with the address of the object.',
    'vcard__postal-code': 'The postal code associated with the address of the object.',
    'vcard__prodid': 'To specify the identifier for the product that created the vCard object.',
    'vcard__region': 'The region (e.g., state or province) associated with the address of the object.',
    'vcard__related': 'To specify a relationship between another entity and the entity represented by this vCard.',
    'vcard__rev': 'To specify revision information about the current vCard.',
    'vcard__role': 'To specify the function or part played in a particular situation by the object.',
    'vcard__sound': 'To specify a digital sound content information that annotates some aspect of the vCard.',
    'vcard__street-address': 'The street address associated with the address of the object.',
    'vcard__tel': 'To specify the telephone number for telephony communication with the object.',
    'vcard__title': 'To specify the position or job of the object.',
    'vcard__tz': 'To specify information related to the time zone of the object.',
    'vcard__uid': 'To specify a value that represents a globally unique identifier corresponding to the entity associated with the vCard.',
    'vcard__url': 'To specify a uniform resource locator associated with the object.',
}

# Known comments for DOAP ontology
DOAP_COMMENTS = {
    'doap__ArchRepository': 'GNU Arch source code repository.',
    'doap__BKRepository': 'BitKeeper source code repository.',
    'doap__BazaarBranch': 'Bazaar source code branch.',
    'doap__CVSRepository': 'CVS source code repository.',
    'doap__DarcsRepository': 'darcs source code repository.',
    'doap__GitBranch': 'Git source code branch.',
    'doap__GitRepository': 'Git source code repository.',
    'doap__HgRepository': 'Mercurial source code repository.',
    'doap__Project': 'A project.',
    'doap__Repository': 'Source code repository.',
    'doap__SVNRepository': 'Subversion source code repository.',
    'doap__Specification': 'A specification of a system aspect, feature or interface.',
    'doap__Version': 'Version information of a project release.',
    'doap__anon_root': 'Repository for anonymous access.',
    'doap__audience': 'Description of target user base.',
    'doap__blog': 'URI of a blog related to a project.',
    'doap__browse': 'Web browser interface to repository.',
    'doap__bug_database': 'Bug tracker for a project.',
    'doap__category': 'A category of project.',
    'doap__created': 'Date when something was created, in YYYY-MM-DD form.',
    'doap__description': 'Plain text description of a project, of 2-4 sentences in length.',
    'doap__developer': 'Developer of software for the project.',
    'doap__documenter': 'Contributor of documentation to the project.',
    'doap__download_mirror': 'Mirror of software download web page.',
    'doap__download_page': 'Web page from which the project software can be downloaded.',
    'doap__file_release': 'URI of download associated with this release.',
    'doap__hasRepository': 'A repository containing the source code for this project.',
    'doap__helper': 'Project contributor.',
    'doap__homepage': 'URL of a projects homepage, associated with exactly one project.',
    'doap__implements': 'A specification that a project implements.',
    'doap__language': 'ISO language code a project has been translated into.',
    'doap__license': 'The URI of an RDF description of the license the software is distributed under.',
    'doap__location': 'Location of a repository.',
    'doap__mailing_list': 'Mailing list home page or email address.',
    'doap__maintainer': 'Maintainer of a project, a project leader.',
    'doap__module': 'Module name of a Subversion, CVS, BitKeeper or Arch repository.',
    'doap__name': 'A name of something.',
    'doap__old_homepage': 'URL of a projects past homepage, associated with exactly one project.',
    'doap__os': 'Operating system that a project is limited to.',
    'doap__platform': 'Indicator of software platform (non-OS specific), e.g. Java, Firefox, ECMA CLR.',
    'doap__programming_language': 'Programming language a project is implemented in or intended for use with.',
    'doap__release': 'A project release.',
    'doap__revision': 'Revision identifier of a software release.',
    'doap__screenshots': 'Web page with screenshots of project.',
    'doap__service_endpoint': 'The URI of a web service endpoint where software as a service may be accessed.',
    'doap__shortdesc': 'Short (8 or 9 words) plain text description of a project.',
    'doap__tester': 'A tester or other quality control contributor.',
    'doap__translator': 'Contributor of translations to the project.',
    'doap__vendor': 'Vendor organization: commercial, free or otherwise.',
    'doap__wiki': 'URL of Wiki for collaborative discussion of project.',
}

# Known comments for SIOC ontology
SIOC_COMMENTS = {
    'sioc__Community': 'Community is a high-level concept that defines an online community and what it consists of.',
    'sioc__Container': 'An area in which content Items are contained.',
    'sioc__Forum': 'A discussion area on which Posts or topics are created.',
    'sioc__Item': 'An Item is something which can be in a Container.',
    'sioc__Post': 'An article or message that can be posted to a Forum.',
    'sioc__Role': 'A Role is a function of a UserAccount within a scope of a particular Forum, Site, etc.',
    'sioc__Site': 'A Site can be the location of an online community or set of communities.',
    'sioc__Space': 'A Space is a place where data resides, e.g. on a website, desktop, fileshare, etc.',
    'sioc__Thread': 'A container for a series of threaded discussion Posts or Items.',
    'sioc__UserAccount': 'A user account in an online community site.',
    'sioc__Usergroup': 'A set of UserAccounts whose members can perform certain functions in a given Space.',
    'sioc__about': 'Specifies that this Item is about a particular resource, e.g. a Post describing a book, a ## on a particular topic, etc.',
    'sioc__account_of': 'Refers to the foaf:Agent or foaf:Person who owns this sioc:UserAccount.',
    'sioc__addressed_to': 'Refers to who (e.g. a UserAccount, e-mail address, etc.) a particular Item is addressed to.',
    'sioc__administrator_of': 'A Site that the UserAccount is an administrator of.',
    'sioc__attachment': 'The URI of a file attached to an Item.',
    'sioc__avatar': 'An image or depiction used to represent this UserAccount.',
    'sioc__container_of': 'An Item that this Container contains.',
    'sioc__content': 'The content of the Item in plain text format.',
    'sioc__content_encoded': 'The encoded content of the Post, contained in CDATA areas.',
    'sioc__created_at': 'When this was created, in ISO 8601 format.',
    'sioc__creator_of': 'A resource that the UserAccount is a creator of.',
    'sioc__description': 'The content of the Post.',
    'sioc__earlier_version': 'Links to a previous (earlier) revision of this Item or Post.',
    'sioc__email': 'An electronic mail address of the UserAccount.',
    'sioc__email_sha1': 'An electronic mail address of the UserAccount, encoded using SHA1.',
    'sioc__embeds_knowledge': 'This links Items to embedded statements, graphs and issues of representation that are logically linked with the Item.',
    'sioc__feed': 'A feed (e.g. RSS, Atom, etc.) pertaining to this resource.',
    'sioc__first_name': 'First (real) name of this user. Synonym for foaf:firstName.',
    'sioc__follows': 'Indicates that one UserAccount follows another UserAccount.',
    'sioc__function_of': 'A UserAccount that has this Role.',
    'sioc__generator': 'A URI for the application used to generate this Item.',
    'sioc__has_administrator': 'A UserAccount that is an administrator of this Site.',
    'sioc__has_container': 'The Container to which this Item belongs.',
    'sioc__has_creator': 'This is the UserAccount that made this resource.',
    'sioc__has_discussion': 'A discussion that is related to this Item.',
    'sioc__has_function': 'A Role that this UserAccount has.',
    'sioc__has_group': 'A Usergroup that has certain access privileges to this Space.',
    'sioc__has_host': 'The Site that hosts this Forum.',
    'sioc__has_member': 'A UserAccount that is a member of this Usergroup.',
    'sioc__has_moderator': 'A UserAccount that is a moderator of this Forum.',
    'sioc__has_owner': 'A UserAccount that this resource is owned by.',
    'sioc__has_parent': 'A Container or Forum that this Container or Forum is a child of.',
    'sioc__has_part': 'An resource that is a part of this subject.',
    'sioc__has_reply': 'Points to an Item or Post that is a reply or response to this Item or Post.',
    'sioc__has_scope': 'A resource that this Role applies to.',
    'sioc__has_space': 'A data Space which this resource is a part of.',
    'sioc__has_subscriber': 'A UserAccount that is subscribed to this Container.',
    'sioc__has_usergroup': 'Points to a Usergroup that has certain access to this Space.',
    'sioc__host_of': 'A Forum that is hosted on this Site.',
    'sioc__id': 'An identifier of a SIOC concept instance.',
    'sioc__ip_address': 'The IP address used when creating this Item.',
    'sioc__last_activity_date': 'The date and time of the last activity associated with a SIOC concept instance.',
    'sioc__last_item_date': 'The date and time of the last Post (or Item) in a Forum (or a Container).',
    'sioc__last_name': 'Last (real) name of this user. Synonym for foaf:lastName.',
    'sioc__last_reply_date': 'The date and time of the last reply Post or Comment.',
    'sioc__later_version': 'Links to a later (newer) revision of this Item or Post.',
    'sioc__latest_version': 'Links to the latest revision of this Item or Post.',
    'sioc__link': 'A URI of a document which contains this SIOC object.',
    'sioc__links_to': 'Links extracted from hyperlinks within a SIOC concept.',
    'sioc__member_of': 'A Usergroup that this UserAccount is a member of.',
    'sioc__mentions': 'Refers to a resource that this Item mentions.',
    'sioc__moderator_of': 'A Forum that a UserAccount is a moderator of.',
    'sioc__modified_at': 'When this was modified, in ISO 8601 format.',
    'sioc__name': 'The name of a SIOC concept instance, e.g. a UserAccount.',
    'sioc__next_by_date': 'Next Item or Post in a given Container sorted by date.',
    'sioc__next_version': 'Links to the next revision of this Item or Post.',
    'sioc__note': 'A note associated with this Item, for example if it has been edited by a UserAccount.',
    'sioc__num_authors': 'The number of unique authors (UserAccounts) who have contributed to this Item, Thread, Post, Forum, etc.',
    'sioc__num_items': 'The number of Items or Posts in a Forum or Container.',
    'sioc__num_replies': 'The number of replies that this Item, Thread, Post, etc. has.',
    'sioc__num_threads': 'The number of Threads (first Posts and their replies) in a Forum.',
    'sioc__num_views': 'The number of times this Item or Forum has been viewed.',
    'sioc__owner_of': 'A resource owned by a particular UserAccount, for example, a Weblog or Image gallery.',
    'sioc__parent_of': 'A child Container or Forum that this Container or Forum is a parent of.',
    'sioc__part_of': 'A resource that the subject is a part of.',
    'sioc__previous_by_date': 'Previous Item or Post in a given Container sorted by date.',
    'sioc__previous_version': 'Links to the previous revision of this Item or Post.',
    'sioc__read_at': 'When this was read, in ISO 8601 format.',
    'sioc__reference': 'Links either Item with an external resource that the Item is referred from/to.',
    'sioc__related_to': 'Related Posts for this Post.',
    'sioc__reply_of': 'Links to an Item or Post which this Item or Post is a reply to.',
    'sioc__scope_of': 'A Role that has a scope of this resource.',
    'sioc__shared_by': 'A UserAccount that this Item is shared with.',
    'sioc__sibling': 'An Item may have a sibling or a twin that exists in a different Container.',
    'sioc__space_of': 'A resource which belongs to this data Space.',
    'sioc__subject': 'Keyword(s) describing subject of the Post.',
    'sioc__subscriber_of': 'A Container that a UserAccount is subscribed to.',
    'sioc__title': 'This is the title (subject line) of the Post.',
    'sioc__topic': 'A topic of interest, linking to the appropriate URI, e.g. in the Open Directory Project or of a SKOS category.',
    'sioc__usergroup_of': 'A Space that the Usergroup has access to.',
}

# Known comments for XSD datatypes
XSD_COMMENTS = {
    'xsd__anyURI': 'Any URI.',
    'xsd__base64Binary': 'Base64-encoded binary data.',
    'xsd__boolean': 'Boolean (true/false).',
    'xsd__byte': 'Signed 8-bit integer.',
    'xsd__date': 'Calendar date.',
    'xsd__dateTime': 'Date and time.',
    'xsd__dateTimeStamp': 'Date and time with required timezone.',
    'xsd__decimal': 'Arbitrary-precision decimal number.',
    'xsd__double': 'IEEE 64-bit floating-point.',
    'xsd__duration': 'Duration of time.',
    'xsd__float': 'IEEE 32-bit floating-point.',
    'xsd__gDay': 'Day of month.',
    'xsd__gMonth': 'Month.',
    'xsd__gMonthDay': 'Month and day.',
    'xsd__gYear': 'Year.',
    'xsd__gYearMonth': 'Year and month.',
    'xsd__hexBinary': 'Hexadecimal-encoded binary data.',
    'xsd__int': 'Signed 32-bit integer.',
    'xsd__integer': 'Arbitrary-precision integer.',
    'xsd__language': 'Language identifier.',
    'xsd__long': 'Signed 64-bit integer.',
    'xsd__negativeInteger': 'Negative integer.',
    'xsd__nonNegativeInteger': 'Non-negative integer.',
    'xsd__nonPositiveInteger': 'Non-positive integer.',
    'xsd__normalizedString': 'Whitespace-normalized string.',
    'xsd__positiveInteger': 'Positive integer.',
    'xsd__short': 'Signed 16-bit integer.',
    'xsd__string': 'Character string.',
    'xsd__time': 'Time of day.',
    'xsd__token': 'Tokenized string.',
    'xsd__unsignedByte': 'Unsigned 8-bit integer.',
    'xsd__unsignedInt': 'Unsigned 32-bit integer.',
    'xsd__unsignedLong': 'Unsigned 64-bit integer.',
    'xsd__unsignedShort': 'Unsigned 16-bit integer.',
}

# Combine all known comments
ALL_COMMENTS = {}
ALL_COMMENTS.update(OWL_COMMENTS)
ALL_COMMENTS.update(DCTERMS_COMMENTS)
ALL_COMMENTS.update(SKOS_COMMENTS)
ALL_COMMENTS.update(FOAF_COMMENTS)
ALL_COMMENTS.update(PROV_COMMENTS)
ALL_COMMENTS.update(TIME_COMMENTS)
ALL_COMMENTS.update(VCARD_COMMENTS)
ALL_COMMENTS.update(DOAP_COMMENTS)
ALL_COMMENTS.update(SIOC_COMMENTS)
ALL_COMMENTS.update(XSD_COMMENTS)


def get_anchors(ns_dir: Path) -> Set[str]:
    """Get all anchor names in this namespace."""
    anchors = set()
    for f in ns_dir.glob('*.md'):
        name = f.stem
        # Anchors don't have spaces and don't start with !
        if ' ' not in name and not name.startswith('!'):
            anchors.add(name)
    return anchors


def get_existing_comments(ns_dir: Path) -> Set[str]:
    """Get anchors that already have rdfs:comment statements."""
    existing = set()
    for f in ns_dir.glob('* rdfs__comment ___.md'):
        # Extract anchor name from file name
        name = f.stem.split(' ')[0]
        existing.add(name)
    return existing


def create_comment_file(ns_dir: Path, anchor: str, comment: str):
    """Create rdfs:comment statement file for an anchor."""
    filename = f"{anchor} rdfs__comment ___.md"
    filepath = ns_dir / filename

    content = f"""---
metadata: statement
rdf__subject: "[[{anchor}]]"
rdf__predicate: "[[rdfs__comment]]"
rdf__object: "{comment}"
---
"""
    filepath.write_text(content)
    print(f"  Created: {filename}")


def generate_missing_comments(ns: str, dry_run: bool = True):
    """Generate missing rdfs:comment statements for a namespace."""
    ns_dir = REPO_ROOT / ns
    if not ns_dir.exists():
        print(f"  Namespace not found: {ns}")
        return

    anchors = get_anchors(ns_dir)
    existing = get_existing_comments(ns_dir)
    missing = anchors - existing

    if not missing:
        print(f"  All anchors have comments")
        return

    print(f"  Missing comments for {len(missing)} anchors")

    for anchor in sorted(missing):
        comment = ALL_COMMENTS.get(anchor, f"TODO: Add description for {anchor}")
        if dry_run:
            print(f"    Would create: {anchor} rdfs__comment ___.md")
            if anchor not in ALL_COMMENTS:
                print(f"      (using placeholder)")
        else:
            create_comment_file(ns_dir, anchor, comment)


def main():
    import argparse
    parser = argparse.ArgumentParser(description='Generate missing rdfs:comment statements')
    parser.add_argument('--namespace', '-n', help='Process only this namespace')
    parser.add_argument('--apply', action='store_true', help='Actually create files (default is dry run)')
    args = parser.parse_args()

    namespaces = [args.namespace] if args.namespace else ['owl', 'dcterms', 'skos', 'foaf', 'prov', 'time', 'vcard', 'doap', 'sioc', 'xsd']

    print("=" * 60)
    print("Generating Missing rdfs:comment Statements")
    print("=" * 60)
    print()

    if not args.apply:
        print("DRY RUN - use --apply to create files")
        print()

    for ns in namespaces:
        print(f"\n{ns.upper()}:")
        generate_missing_comments(ns, dry_run=not args.apply)


if __name__ == '__main__':
    main()
